### PR TITLE
New blocks

### PR DESCRIPTION
**Pull request by veggiecan0419**

### CODE REVIEW

**Comment by veggiecan0419** [comment]
@SharkPool-SP Is this how you wanted it?
Other blocks will still come.

(Formatted as well)

Feel free to edit the code.

**Comment by SharkPool-SP** [comment]
> @SharkPool-SP Is this how you wanted it? Other blocks will still come.
> 
> (Formatted as well)
> 
> Feel free to edit the code.

this still requires the VM edits right

**Comment by veggiecan0419** [comment]
> > @SharkPool-SP Is this how you wanted it? Other blocks will still come.
> > (Formatted as well)
> > Feel free to edit the code.
> 
> this still requires the VM edits right

@SharkPool-SP Well, it depends what you mean with `edits`. It doesn't require any changes to TurboWarp/scratch-vm repo, but it does override a VM function (as it should also go off with the vanilla block too, (and Lily/MoreEvents)).

**Comment by SharkPool-SP** [comment]
> > > @SharkPool-SP Is this how you wanted it? Other blocks will still come.
> > > (Formatted as well)
> > > Feel free to edit the code.
> > 
> > 
> > this still requires the VM edits right
> 
> @SharkPool-SP Well, it depends what you mean with `edits`. It doesn't require any changes to TurboWarp/scratch-vm repo, but it does override a VM function (as it should also go off with the vanilla block too, (and Lily/MoreEvents)).

just tested, it doesnt work. You cant use startHats on any block with a text/reporter menu

**Comment by SharkPool-SP** [comment]
right so Im not merging this, its done wrong + I dont need the blocks no offense.

I just worked around it myself:
image

**Comment by veggiecan0419** [comment]
So how did you do it?

> right so Im not merging this, its done wrong + I dont need the blocks no offense.
> 
> I just worked around it myself: image

**Comment by SharkPool-SP** [comment]
> So how did you do it?
> 
> > right so Im not merging this, its done wrong + I dont need the blocks no offense.
> > I just worked around it myself: image

look at the code

**Comment by veggiecan0419** [comment]
I think the blocks would still be useful tho

**Comment by SharkPool-SP** [comment]
> I think the blocks would still be useful tho

I doubt it, especially since variables and this block can work around it

**Comment by veggiecan0419** [comment]
OK.
I'll still see if I can get it to work. If so, and you still don't want it, that's perfectly fine.

**Comment by veggiecan0419** [comment]
> > I think the blocks would still be useful tho
> 
> I doubt it, especially since variables and this block can work around it

https://github.com/TurboWarp/extensions/pull/639#issuecomment-1625343274
That's why I thought it would be useful

**Comment by veggiecan0419** [comment]
I was going to add an `any message` option to the when broadcast received, and a `broadcast name` block if you see my original PR.

**Comment by SharkPool-SP** [comment]
Ok

**Pull request closed without merging**
